# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Des Moines Web Collective
email: kjbrumm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A community of web professionals in the Des Moines metro area.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dsmwebcollective.com" # the base hostname & protocol for your site
twitter_username: dsmwebcollective
facebook_username: dsmwebcollective

# Build settings
markdown: kramdown
